### ISSUE TITLE
Parcel 不可用于操作系统分配 RHEL6

### ISSUE THREAD

**Issue by dashenstone** [JINGXI6/elasticsearch-cdh-parcels#1]
Parcel ELASTICSEARCH-7.9.0-el6 的错误：Parcel 不可用于操作系统分配 RHEL6

**Comment by JINGXI6** [comment]
你的操作系统是centos6.x？稍等我会提交一个6.x的打包脚本，你可以试一下

**Comment by JINGXI6** [comment]
@jczk 重新安装试下 /bin/bash install -d /opt/cloudera -t all -u true -v el6
