### ISSUE TITLE
未找到哈希文件

### ISSUE THREAD

**Issue by dashenstone** [JINGXI6/elasticsearch-cdh-parcels#3]
Parcel ELASTICSEARCH-7.9.0-el6.parcel 的错误：未找到哈希文件。

**Comment by JINGXI6** [comment]
看一下你cloudera/parcels-repo 目录下有什么文件

**Comment by dashenstone** [comment]
> 看一下你cloudera/parcels-repo 目录下有什么文件

LASTICSEARCH-7.9.0-el6.parcel
ELASTICSEARCH-7.9.0-el6.parcel.sha
就这2个文件，没有 manifest.json文件，ClouderaManager的Parcel就报这个错。
方便加QQ或邮箱不尼？

**Comment by JINGXI6** [comment]
> > 看一下你cloudera/parcels-repo 目录下有什么文件
> 
> LASTICSEARCH-7.9.0-el6.parcel
> ELASTICSEARCH-7.9.0-el6.parcel.sha
> 就这2个文件，没有 manifest.json文件，ClouderaManager的Parcel就报这个错。
> 方便加QQ或邮箱不尼？

Qq 1194879789

**Comment by JINGXI6** [comment]
python确定为2.7.x版本，重新安装
